config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about',to:'pages#about'  
  get 'signup',to:'users#new'
  resources:articles ,only: [:show, :index, :new, :create, :edit, :update, :destroy]
  resources:users,except:[:new]
  get 'login',to:"sessions#new"
  post 'login',to:"sessions#create"
  delete 'logout',to:'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article<ApplicationRecord
    validates:title,presence:true,length:{minimum:6,maximum:10}
    validates:description,presence:true,length:{minimum:10,maximum:300}
    belongs_to :user
end    

app/models/user.rb
class User<ApplicationRecord
    before_save {self.email=email.downcase}
    has_many:articles ,dependent: :destroy  
    validates:username,presence:true,uniqueness: {case_sensitive:false},length:{minimum:3,maximum:25}
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i  
    validates:email,presence:true,uniqueness: {case_sensitive:false},length:{maximum:105},format: { with: VALID_EMAIL_REGEX}
    
    has_secure_password
end    

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user,:logged_in?
    def current_user
        if session[:user_id]
            @current_user ||=User.find(session[:user_id])
        end    
    end    

    def logged_in?
        !!current_user
    end    
    def req_user
        if !logged_in?
            flash[:alert]="Need to login"
            redirect_to 'login'
        end    
    end    
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only: [:show,:edit,:update,:destroy]
    before_action :req_user,except:[:show,:index]
    before_action :same_user_req,only: [:edit,:delete]
    def show
    end    
    def index
        @article=Article.paginate(page: params[:page], per_page: 3)

    end
    def new
        if logged_in?
            @article=Article.new()  
        else
            redirect_to signup_path
        end          
    end
    
    def create 
        # byebug
        @article=Article.new(article_params)
        @article.user=current_user
        if @article.save
            flash[:notice]="Article was succesfully created"
            redirect_to @article
        else
            flash[:warning]="Retry"
            render 'new'   
        end    
    end    
    def edit
    
    end
    def update
        if @article.update(article_params)
            flash[:notice]="Article updated"
            redirect_to @article
        else
            render 'edit'
        end        
    end    
    def destroy
         @article.destroy
        redirect_to articles_path
    end    

    private
    def set_article
        @article=Article.find(params[:id])
    end    

    def article_params
        params.require(:article).permit(:title,:description)
    end   
    def same_user_req
        if current_user!=@article.user
            flash[:alert]="You can only edit your articles"
            redirect_to @article
        end    
    end    
end    

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
        if logged_in?
            redirect_to articles_path
        end    
    end
    def about
    end    
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end
    def create
        user=User.find_by(email:params[:session][:email])
        if user && user.authenticate(params[:session][:password])
            session[:user_id]=user.id
            flash[:notice]="Logged in #{user.username}"
            redirect_to user
        else
            flash.now[:alert]="Incorect"
            render 'new' 
        end       
    end
    def destroy
        session[:user_id]=nil
        flash[:notice]="Logged out"
        redirect_to root_path
    end            
end    

app/controllers/users_controller.rb
class UsersController<ApplicationController
    before_action :req_user,only:[:edit,:update]
    def new
        @user=User.new()
    end
    def create
       @user=User.new(params.require(:user).permit(:username,:email,:password)) 
       if @user.save
        session[:user_id]=@user.id
        flash[:notice]="Welcome to the blog #{@user.username}"
        @user.save
        redirect_to users_path
       else
        render 'new'
       end  
    end    
    def index
        @user=User.paginate(page:params[:page],per_page:30)
    end    
    def show
        @user=User.find(params[:id])
    end    
    def edit
        @user=User.find(params[:id])
    end
    def update
        @user=User.find(params[:id])
        if @user.update(params.require(:user).permit(:username,:email,:password))
            flash[:notice]="USer updated #{@user.username}      "
            redirect_to users_path
        else
            render 'edit' 
        end       
    end   
    def destroy
        @user=User.find(params[:id])     
        @user.destroy
        session[:user_id]=nil
        
        flash[:notice]="User Deleted"
        redirect_to articles_path
    end    
end

app/helpers/application_helper.rb
module ApplicationHelper
    
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_form.html.erb
<div class="container">
<%if @article.errors.any?%>
    <ul>
    <%@article.errors.full_messages.each do |message|%>
        <li><%= message%></li>
    <%end%>
    </ul>
<%end%>        

<div class="row justify-content-center">
    <div class="col-10">
        <%=form_with(model:@article,class:"bg-info shadow p-3 mb-3",local: true) do |f| %>
            <div class="form-group row">
                <%=f.label :title,class:"col-2 col-form-label"%>
                <div class="col-10">
                    <%=f.text_field :title,class:"form-control shadow",placeholder:"Title"%>
                </div>
            </div>
            <div class="form-group row">
                <%=f.label :description,class:"col-2 col-form-label"%>
                <div class="col-10">
                    <%=f.text_area :description,rows:10, class:"form-control shadow"%>
                </div>
            </div>   
            <div class="form-group row justify-content-center">
                <%=f.submit class:"btn btn-outline-success"%><br/>
            </div>
        <%end%>  
      <%=link_to "Return to index", articles_path,class:"text-info" %>
    </div> 
</div>      

app/views/articles/edit.html.erb
<p>Edit article</p>

<%=render 'form'%>

app/views/articles/index.html.erb
<h1 class="text-center pt-3 pb-3">Listing all articles</h1>
<div class="flickr_pagination mb-3">
    <%= will_paginate @article, :container => false %>
  </div>
<% @article.each do |article|%> 
    
<div class="container"> 
    <div class="row d-flex justify-content-center">
        <div class="col-8">
            <div class="card text-center mb-3 shadow">
                <div class="card-header">
                <%=link_to article.user.username,users_path%>
                </div>
                <div class="card-body">
                    <h5 class="card-title"><%=link_to  article.title ,article_path(article),class:"text-success"%></h5>
                    <p class="card-text"><%= article.description%></p>
                    <%=link_to 'View',article_path(article),class:"btn btn-outline-primary"%>
                    <% if logged_in? && current_user==article.user%>
                        <%= link_to 'Edit',edit_article_path(article),class:"btn btn-outline-success"%>
                        <%= link_to 'Delete',article_path(article),method: :delete,class:"btn btn-outline-warning",data: {confirm:"SUre?"}%>
                    <%end%>    
                </div>
                <div class="card-footer text-muted">
                    <%=article.created_at%>
                </div>
            </div>
        </div>
    </div>
</div>       
<%end%>
<div class="flickr_pagination mb-3">
    <%= will_paginate @article, :container => false %>
  </div>    
    
    

app/views/articles/new.html.erb
<h1 class="text-center">Create new Article </h1>
<%= render 'form'%>

app/views/articles/show.html.erb
<div class="bg-color">
<div class="container">
<h1 class="text-center pt-3 pb-5"><%=@article.title%></h1
>
<div class="row d-flex justify-content-center">
        <div class="col-8">
            <div class="card text-center mb-3 shadow">
                <div class="card-header">
                        by <%= @article.user.username%>
                </div>
                <div class="card-body">
                    <p class="card-text"><%= @article.description%></p>
                    <%= link_to 'Edit',edit_article_path(@article),class:"btn btn-outline-success"%>
                    
                    <%= link_to 'Delete',article_path(@article),method: :delete,class:"btn btn-outline-warning",data: {confirm:"SUre?"}%>
                </div>
                <div class="card-footer text-muted">
                    <p>created_at:<%=time_ago_in_words(@article.created_at)%></p>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  
  <%= link_to 'ALPHA-BLOG',articles_path,class:"navbar-brand"%>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        
        <%= link_to "Bloggers",users_path,class:"nav-link"%>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
         <%if logged_in?%>
          <%=link_to 'Create Articles',new_article_path,class:"dropdown-item"%>
          <%end%>
          <%=link_to 'View Articles',articles_path,class:"dropdown-item"%>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <%if logged_in?%>
        <li class="nav-item">
            <%= link_to 'Logout',logout_path,class:"nav-link",method: :delete%>
        </li>
      <%else%>
        <li class="nav-item">
            <%= link_to 'Login',login_path,class:"nav-link"%>
        </li>     
        <li class="nav-item">
            <%= link_to 'Signup',signup_path,class:"nav-link"%>
         </li>   
      <%end%>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Alphablog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation'%>
    
    <%flash.each do |name,msg|%>
      <%if (name=="notice")%>
        <div class="alert alert-success" role="alert">
          <%=msg%>
        </div>
       <%else%>
       <div class="alert alert-warning" role="alert">
       <%=msg%>
     </div>
    <%end%>  
  <%end%>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<p>This is about page</p>

app/views/pages/home.html.erb
<div class="container mt-3 text-center">
<div class="jumbotron text-white">
  <h1 class="display-4">AlphaBlog</h1>
  <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
  <hr class="my-4">
  <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
  <%=link_to 'SignUp',signup_path,class:"btn btn-success"%>
</div>
</div>

app/views/users/_form.html.erb
<div class="container"> 
<%if @user.errors.any?%>
<%=@user.class.name.downcase%>
<ul>

    <% @user.errors.full_messages.each do |error|%>
        <li><%=error%></li>
    <%end%>    
 </ul>   
<%end%>      
<div class="row justify-content-center">
    <div class="col-10">
        <%=form_with(model:@user,class:"bg-info shadow p-3 mb-3",local: true) do |f| %>
            <div class="form-group row">
                <%=f.label :username,class:"col-2 col-form-label"%>
                <div class="col-10">
                    <%=f.text_field :username,class:"form-control shadow",placeholder:"username"%>
                </div>
            </div>
            <div class="form-group row">
                <%=f.label :email,class:"col-2 col-form-label"%>
                <div class="col-10">
                    <%=f.email_field :email,rows:10, class:"form-control shadow",placeholder:"Valid Email"%>
                </div>
            </div>  
            <div class="form-group row">
                <%=f.label :password,class:"col-2 col-form-label"%>
                <div class="col-10">
                    <%=f.password_field :password,rows:10, class:"form-control shadow",placeholder:"Create Password"%>
                </div>
            </div>   
            <div class="form-group row justify-content-center">
                <%=f.submit(@user.new_record? ? "signup": "update account",class:"btn btn-outline-success")%><br/>
            </div>
        <%end%>  
      <%=link_to "Return to index", articles_path,class:"text-info" %>
    </div> 
</div>      

app/views/users/edit.html.erb
<h1 class="text-center mt-3">Edit the Users</h1>
<%=render 'form'%>  

app/views/users/index.html.erb
<h1 class="text-center mt-3">User Profiles</h1>
<% @user.each do |user|%>
<div class="row d-flex justify-content-center">
        <div class="col-5">
            <div class="card text-center mb-3 shadow">
                <div class="card-header">
                        <%= user.username%>
                </div>
                <div class="card-body">
                    <p class="card-text"><%= user.articles.count%> articles</p>
                     <%=link_to 'View',user_path(user),class:"btn btn-outline-primary"%> 
                     <%if logged_in? && current_user=user%>  
                    <%= link_to 'Edit',edit_user_path(user),class:"btn btn-outline-success"%>
                    <%= link_to 'Delete',article_path(user),method: :delete,class:"btn btn-outline-warning",data: {confirm:"SUre?"}%>
                    <%end%>   
                 </div>
                <div class="card-footer text-muted">
                    <p>created_at:<%=time_ago_in_words(user.created_at)%></p>
                </div>
            </div>
        </div>
<%end%>        
</div>

app/views/users/new.html.erb
<h1 class="text-center mt-4">Create new users</h1>
<%= render 'form' %>

app/views/users/show.html.erb
<div class="bg-color">
<div class="container">
<h1 class="m-auto mt-3 pb-3 bg-primary col-5">Hello <%=  @user.username%></h1>
<% @user.articles.each do |article|%>
<div class="row d-flex justify-content-center">
        <div class="col-8">
            <div class="card text-center mb-3 shadow">
                <div class="card-header">
                        by <%= article.title%>
                </div>
                <div class="card-body">
                    <p class="card-text"><%= article.description%></p>
                    <%= link_to 'View',article_path(article),class:"btn btn-primary"%>
                    <%= link_to 'Edit',edit_article_path(article),class:"btn btn-outline-success"%>
                    
                    <%= link_to 'Delete',article_path(article),method: :delete,class:"btn btn-outline-warning",data: {confirm:"SUre?"}%>
                </div>
                <div class="card-footer text-muted">
                    <p>created_at:<%=time_ago_in_words(article.created_at)%></p>
                </div>
            </div>
        </div>
<%end%>        
</div>
<p class=text-center><%=link_to 'Delete User',user_path(@user),method: :delete,class:"btn btn-outline-warning",data: {confirm:"rey sure?"}%></p>
</div>
</div>